name: CI to Docker Hub

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  URL_ROOT: 'http://localhost'
  MAX_API_KEY_USAGE: '30'
  CORN_SECOND: 0 
  CORN_MINUTE: 0
  CORN_HOUR: 0
  MONGO_URL: "mongodb+srv://sa:admin@cluster0.wdqxg.mongodb.net/coodesh-back-end?retryWrites=true&w=majority"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: latest, ${{github.run_number}}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
